const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnURLFailed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Acts.UnloadObjectTextures,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Sprite.Acts.AddRemoveAnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Sprite.Cnds.CompareHeight
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Logo: 0},
	{Sponsorship: 0},
	{AJAX: 0},
	{Dictionary: 0},
	{JSON: 0},
	{Debug: 0},
	{Touch: 0},
	{StatusNo: 0},
	{DefaultFishFacing: 0},
	{FishFacing: 0},
	{FishAngle: 0},
	{Speed: 0},
	{DefaultFrame: 0},
	{Frame: 0},
	{Random: 0},
	{FishID: 0},
	{FishNo: 0},
	{FishFile: 0},
	{FishFile2: 0},
	{NameFrame: 0},
	{Status: 0},
	{NameFile: 0},
	{BorningPointX: 0},
	{BorningPointY: 0},
	{拖放: 0},
	{house: 0},
	{Eye: 0},
	{Fade: 0},
	{Train1: 0},
	{NameParentUID: 0},
	{NameF: 0},
	{NameID: 0},
	{NameNo: 0},
	{DragDrop: 0},
	{name1: 0},
	{name2: 0},
	{MouseDetect: 0},
	{Mouse: 0},
	{recycle: 0},
	{Star: 0},
	{Keyboard: 0},
	{Particles: 0},
	{Gift: 0},
	{GiftReturn: 0},
	{background2: 0},
	{Giftlist: 0},
	{GO: 0},
	{AdvancedRandom: 0},
	{ResetDraw: 0},
	{Giftlist2: 0},
	{Audio: 0},
	{Giftlist3: 0},
	{Fish: 0},
	{Name: 0},
	{LogoNo: 0},
	{spno: 0},
	{counter: 0},
	{FishCount1: 0},
	{FishCount2: 0},
	{FishCount3: 0},
	{FishFileCount1: 0},
	{FishFileCount2: 0},
	{FishFileCount3: 0},
	{LastFishFileCount1: 0},
	{LastFishFileCount2: 0},
	{LastFishFileCount3: 0},
	{LastFishImage1: 0},
	{LastFishImage2: 0},
	{LastFishImage3: 0},
	{FishCreateCount1: 0},
	{FishCreateCount2: 0},
	{FishCreateCount3: 0},
	{FishTotalCount: 0},
	{JsonF1: 0},
	{JsonF2: 0},
	{JsonF3: 0},
	{screenmax1: 0},
	{screenmax2: 0},
	{screenmax3: 0},
	{screenmax4: 0},
	{screenmax5: 0},
	{TotalFish1: 0},
	{TotalFish2: 0},
	{TotalFish3: 0},
	{TotalFish4: 0},
	{TotalFish5: 0},
	{TotalFishAll: 0},
	{CheckTime: 0},
	{EnterTime: 0},
	{NameDisplaynum: 0},
	{LocalFish: 0},
	{LocalFish2: 0},
	{dtt: 0},
	{dtt2: 0},
	{IndexPath: 0},
	{Mode: 0},
	{MovingSpeed: 0},
	{AnimationType: 0},
	{CounterTime: 0},
	{GiftTime: 0},
	{EventID: 0},
	{debugvaluable: 0},
	{DrawGameStatus: 0},
	{f1: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Sponsorship: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	JSON: class extends self.IJSONInstance {},
	Debug: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	house: class extends self.ISpriteInstance {},
	Train1: class extends self.ISpriteInstance {},
	name1: class extends self.ISpriteInstance {},
	name2: class extends self.ISpriteInstance {},
	MouseDetect: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	recycle: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Gift: class extends self.ISpriteInstance {},
	GiftReturn: class extends self.ISpriteInstance {},
	background2: class extends self.ISpriteInstance {},
	Giftlist: class extends self.ISpriteInstance {},
	GO: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	ResetDraw: class extends self.ISpriteInstance {},
	Giftlist2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Giftlist3: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	Name: class extends self.ISpriteInstance {}
}